account_types = {
    "Cash": "Assets Account",
    "Savings account": "Assets Account",
    "Petty cash balance": "Assets Account",
    "Accounts receivable": "Assets Account",
    "Undeposited funds": "Assets Account",
    "Inventory assets": "Assets Account",
    "Prepaid insurance": "Assets Account",
    "Accounts Receivable": "Assets Account",
    "Advance to Suppliers": "Assets Account",
    "Employee Advances": "Assets Account",
    "Deposits": "Assets Account",
    "Long-Term Investments": "Assets Account",
    "Short-Term Investments": "Assets Account",
    "Prepaid Rent": "Assets Account",
    "Prepaid Taxes": "Assets Account",
    "salary Advance": "Assets Account",
    "Fee Paid House Rent Allowance": "Assets Account",
    "Fee Paid Telephone expenses": "Assets Account",
    "Fee Paid Income Tax": "Assets Account",
    "Fee Paid Guest House Charges": "Assets Account",
    "Performance Salary": "Cost Account",
    "Incentive to Staff": "Cost Account",
    "House Rent Allowance": "Cost Account",
    "Basic salary": "Cost Account",
    "Transport Allowance": "Cost Account",
    "Site Allowance": "Cost Account",
    "Site Visit": "Cost Account",
    "Stipend Account": "Cost Account",
    "Recruitment Expenses": "Cost Account",
    "Telephone expenses reimbursement": "Cost Account",
    "Medical Expenses reimbursement": "Cost Account",
    "Staff Welfare (In office)": "Cost Account",
    "Staff Welfare (Out of office)": "Cost Account",
    "Staff Insurance": "Cost Account",
    "Festival Expenses": "Cost Account",
    "Income Tax Expenses": "Cost Account",
    "Service Tax Expenses": "Cost Account",
    "Office maintenance": "Cost Account",
    "Conveyance Expenses - Employees": "Cost Account",
    "Travelling Expenses -Domestic": "Cost Account",
    "Business Development cost": "Cost Account",
    "Travelling Expenses -Foreign": "Cost Account",
    "Free/Concessional tkts to staff": "Cost Account",
    "Cellular Phone Expenses": "Cost Account",
    "Telephone Expenses": "Cost Account",
    "Telephone Expenses (Petty)": "Cost Account",
    "Courier Expenses": "Cost Account",
    "Postage Expenses": "Cost Account",
    "Laisoning Expenditure": "Cost Account",
    "Printing & Stationery": "Cost Account",
    "Vehicle insurance (Non commercial)": "Cost Account",
    "Vehicle insurance (Commercial)": "Cost Account",
    "Lease Rent": "Cost Account",
    "Rent": "Cost Account",
    "Guest House Rent": "Cost Account",
    "Guest House Rent payable": "Cost Account",
    "Legal & Professional Charges": "Cost Account",
    "Consultancy Charges": "Cost Account",
    "Professional Tax": "Cost Account",
    "Software Expenses": "Cost Account",
    "Membership fees": "Cost Account",
    "Newpapers, Books & Periodicals Expenses": "Cost Account",
    "Security Expenses": "Cost Account",
    "Text / Reference Books": "Cost Account",
    "Meeting & Conference Expenses": "Cost Account",
    "Advertisement Expenses": "Cost Account",
    "Vehicle Fuel Expenses- Non commercial": "Cost Account",
    "Vehicle Fuel l Expenses- Commercial": "Cost Account",
    "Car Expenses": "Cost Account",
    "Business Promotion Expenses": "Cost Account",
    "Sales Promotion Expenses": "Cost Account",
    "Office Purchases": "Cost Account",
    "Electricity & Generator Expenses": "Cost Account",
    "Guest House Charges": "Cost Account",
    "Repair & Maintenance- Equip & Machinery": "Cost Account",
    "Vehicle Maintenance (Non commercial)": "Cost Account",
    "Repair & Maintenance- Building": "Cost Account",
    "Repair & Maintenance - Others": "Cost Account",
    "Bank Charges": "Cost Account",
    "Short & Excess expenses": "Cost Account",
    "Donation": "Cost Account",
    "Interest on bank loan": "Cost Account",
    "Interest on Vehicle Loans (Non commercial)": "Cost Account",
    "Interest on Vehicle Loans (Commercial)": "Cost Account",
    "Interest on Other Loan": "Cost Account",
    "Audit expenses": "Cost Account",
    "Finance charges": "Cost Account",
    "Training & Development": "Cost Account",
    "Employee Bonus": "Cost Account",
    "Gratuity Expenses": "Cost Account",
    "Depreciation Expense": "Cost Account",
    "Bad Debts Expense": "Cost Account",
    "Office Supplies": "Cost Account",
    "Water & Electricity Charges": "Cost Account",
    "Internet Expenses": "Cost Account",
    "Travel Allowance – International": "Cost Account",
    "Entertainment Expenses": "Cost Account",
    "Cleaning & Housekeeping Expenses": "Cost Account",
    "Bank Service Charges": "Cost Account",
    "Freight & Shipping Charges": "Cost Account",
    "Warranty Expenses": "Cost Account",
    "Loss on Asset Disposal": "Cost Account",
    "Insurance Premium Expense": "Cost Account",
    "Software Subscription Fees": "Cost Account",
    "IT Support Charges": "Cost Account",
    "Outsourcing Charges": "Cost Account",
    "Retained earnings": "Equity Accont",
    "Share Capital": "Equity Accont",
    "Share Premium": "Equity Accont",
    "General Reserve": "Equity Accont",
    "Capital Reserve": "Equity Accont",
    "Revaluation Reserve": "Equity Accont",
    "Partner’s Capital Account": "Equity Accont",
    "Director Capitl Account": "Equity Accont",
    "Drawing Account (for proprietorship/partnership)": "Equity Accont",
    "Office Equipment": "Fixed Asset",
    "Furniture & Fixtures": "Fixed Asset",
    "Land": "Fixed Asset",
    "Plant & Machinery": "Fixed Asset",
    "Computers & Laptops": "Fixed Asset",
    "Printers & Office Equipment": "Fixed Asset",
    "Leasehold Improvements": "Fixed Asset",
    "Motor Vehicles": "Fixed Asset",
    "Buildings under Construction": "Fixed Asset",
    "Vehicles": "Fixed Asset",
    "Buildings": "Fixed Asset",
    "income": "Income Account",
    "Sales Revenue": "Income Account",
    "Revenue": "Income Account",
    "Service Income": "Income Account",
    "Income": "Income Account",
    "Commission Income": "Income Account",
    "Rental Income": "Income Account",
    "Interest Income": "Income Account",
    "Dividend Income": "Income Account",
    "Gain on Sale of Assets": "Income Account",
    "Foreign Exchange Gain": "Income Account",
    "Royalty Income": "Income Account",
    "Miscellaneous Income": "Income Account",
    "Revenue from Car Sales": "Income Account",
    "Revenue from Land Sales": "Income Account",
    "Sofwarre": "Intangible Assets",
    "Company credit card": "Liabilities Account",
    "Accrued liabilities": "Liabilities Account",
    "Accounts payable": "Liabilities Account",
    "Payroll liabilities": "Liabilities Account",
    "Notes payable": "Liabilities Account",
    "Long-Term Loans Payable": "Liabilities Accounts",
    "Short-Term Loans Payable": "Liabilities Accounts",
    "Accrued Salaries": "Liabilities Accounts",
    "Accrued Rent": "Liabilities Accounts",
    "Accrued Utilities": "Liabilities Accounts",
    "Tax Payable": "Liabilities Accounts",
    "VAT Payable / GST Payable": "Liabilities Accounts",
    "Pension Fund Liabilities": "Liabilities Accounts",
    "Social Security Liabilities": "Liabilities Accounts",
    "Customer Advances / Unearned Revenue": "Liabilities Accounts",
    "GST Payable": "Liabilities Accounts",
    "VAT Payable": "Liabilities Accounts"
}
